In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/mrinmoymahato/hackathon_code/dis_sym_dataset_comb.csv')

In [24]:
df

label_dis  abdominal cramp  abdominal distention  abnormal behavior  \
0             0                0                     0                  0   
1             0                0                     0                  0   
2             0                0                     0                  0   
3             0                0                     0                  0   
4             0                0                     0                  0   
...         ...              ...                   ...                ...   
8830        260                0                     0                  0   
8831        260                0                     0                  0   
8832        260                0                     0                  0   
8833        260                0                     0                  0   
8834        260                0                     0                  0   

      abnormal bleeding  abnormal sensation  abnormally frequent  abscess  \
0                     0                   0                    0        0   
1                     0                   0                    0        0   
2                     0                   0                    0        0   
3                     0                   0                    0        0   
4                     0                   0                    0        0   
...                 ...                 ...                  ...      ...   
8830                  0                   0                    0        0   
8831                  0                   0                    0        0   
8832                  0                   0                    0        0   
8833                  0                   0                    0        0   
8834                  0                   0                    0        0   

      aching  acne  ...  wet  wheezing  white patch vaginal discharge  \
0          0     0  ...    0         0                              0   
1          0     0  ...    0         0                              0   
2          0     0  ...    0         0                              0   
3          0     0  ...    0         0                              0   
4          0     0  ...    0         0                              0   
...      ...   ...  ...  ...       ...                            ...   
8830       0     0  ...    0         0                              0   
8831       0     0  ...    0         0                              0   
8832       0     0  ...    0         0                              0   
8833       0     0  ...    0         0                              0   
8834       0     0  ...    0         0                              0   

      widespread pain  withdrawal occurring stopping  worrying  yellow skin  \
0                   0                              0         0            0   
1                   0                              0         0            0   
2                   0                              0         0            0   
3                   0                              0         0            0   
4                   0                              0         0            0   
...               ...                            ...       ...          ...   
8830                0                              0         0            0   
8831                0                              0         0            0   
8832                0                              0         0            0   
8833                0                              0         0            0   
8834                0                              0         0            0   

      yellowish coloration skin white eye  yellowish skin  \
0                                       0               0   
1                                       0               0   
2                                       0               0   
3                                       0               0   
4                        

In [4]:
dict_diseases = dict(enumerate(df.label_dis.unique()))

In [5]:
dict_diseases

{0: 'Abscess',
 1: 'Acquired Capillary Haemangioma of Eyelid',
 2: 'Acquired Immuno Deficiency Syndrome',
 3: 'Acute encephalitis syndrome',
 4: 'Adult Inclusion Conjunctivitis',
 5: 'Alcohol Abuse and Alcoholism',
 6: 'Alopecia (hair loss)',
 7: 'Alzheimer',
 8: 'Amaurosis Fugax',
 9: 'Amblyopia',
 10: 'Amoebiasis',
 11: 'Anaemia',
 12: 'Aniseikonia',
 13: 'Anisometropia',
 14: 'Antepartum hemorrhage (Bleeding in late pregnancy)',
 15: 'Anthrax',
 16: 'Anxiety',
 17: 'Appendicitis',
 18: 'Arthritis',
 19: 'Asbestos-related diseases',
 20: 'Aseptic meningitis',
 21: 'Asthma',
 22: 'Astigmatism',
 23: 'Atrophy',
 24: 'Autism',
 25: 'Bad Breath (Halitosis)',
 26: "Bell's Palsy",
 27: 'Beriberi',
 28: 'Black Death',
 29: 'Bleeding Gums',
 30: 'Blindness',
 31: 'Botulism',
 32: 'Brain Tumour',
 33: 'Breast Cancer / Carcinoma',
 34: 'Bronchitis',
 35: 'Brucellosis',
 36: 'Bubonic plague',
 37: 'Bunion',
 38: 'Burns',
 39: 'Calculi',
 40: 'Campylobacter infection',
 41: 'Cancer',
 42: 'Candi

In [6]:
dict_diseases_inv = {v: k for k, v in dict_diseases.items()}

In [7]:
dict_diseases_inv

{'Abscess': 0,
 'Acquired Capillary Haemangioma of Eyelid': 1,
 'Acquired Immuno Deficiency Syndrome': 2,
 'Acute encephalitis syndrome': 3,
 'Adult Inclusion Conjunctivitis': 4,
 'Alcohol Abuse and Alcoholism': 5,
 'Alopecia (hair loss)': 6,
 'Alzheimer': 7,
 'Amaurosis Fugax': 8,
 'Amblyopia': 9,
 'Amoebiasis': 10,
 'Anaemia': 11,
 'Aniseikonia': 12,
 'Anisometropia': 13,
 'Antepartum hemorrhage (Bleeding in late pregnancy)': 14,
 'Anthrax': 15,
 'Anxiety': 16,
 'Appendicitis': 17,
 'Arthritis': 18,
 'Asbestos-related diseases': 19,
 'Aseptic meningitis': 20,
 'Asthma': 21,
 'Astigmatism': 22,
 'Atrophy': 23,
 'Autism': 24,
 'Bad Breath (Halitosis)': 25,
 "Bell's Palsy": 26,
 'Beriberi': 27,
 'Black Death': 28,
 'Bleeding Gums': 29,
 'Blindness': 30,
 'Botulism': 31,
 'Brain Tumour': 32,
 'Breast Cancer / Carcinoma': 33,
 'Bronchitis': 34,
 'Brucellosis': 35,
 'Bubonic plague': 36,
 'Bunion': 37,
 'Burns': 38,
 'Calculi': 39,
 'Campylobacter infection': 40,
 'Cancer': 41,
 'Candidias

In [8]:
df_mod = df

In [9]:
df_mod.label_dis = df_mod.label_dis.map(dict_diseases_inv)

In [10]:
df_mod

label_dis  abdominal cramp  abdominal distention  abnormal behavior  \
0             0                0                     0                  0   
1             0                0                     0                  0   
2             0                0                     0                  0   
3             0                0                     0                  0   
4             0                0                     0                  0   
...         ...              ...                   ...                ...   
8830        260                0                     0                  0   
8831        260                0                     0                  0   
8832        260                0                     0                  0   
8833        260                0                     0                  0   
8834        260                0                     0                  0   

      abnormal bleeding  abnormal sensation  abnormally frequent  abscess  \
0                     0                   0                    0        0   
1                     0                   0                    0        0   
2                     0                   0                    0        0   
3                     0                   0                    0        0   
4                     0                   0                    0        0   
...                 ...                 ...                  ...      ...   
8830                  0                   0                    0        0   
8831                  0                   0                    0        0   
8832                  0                   0                    0        0   
8833                  0                   0                    0        0   
8834                  0                   0                    0        0   

      aching  acne  ...  wet  wheezing  white patch vaginal discharge  \
0          0     0  ...    0         0                              0   
1          0     0  ...    0         0                              0   
2          0     0  ...    0         0                              0   
3          0     0  ...    0         0                              0   
4          0     0  ...    0         0                              0   
...      ...   ...  ...  ...       ...                            ...   
8830       0     0  ...    0         0                              0   
8831       0     0  ...    0         0                              0   
8832       0     0  ...    0         0                              0   
8833       0     0  ...    0         0                              0   
8834       0     0  ...    0         0                              0   

      widespread pain  withdrawal occurring stopping  worrying  yellow skin  \
0                   0                              0         0            0   
1                   0                              0         0            0   
2                   0                              0         0            0   
3                   0                              0         0            0   
4                   0                              0         0            0   
...               ...                            ...       ...          ...   
8830                0                              0         0            0   
8831                0                              0         0            0   
8832                0                              0         0            0   
8833                0                              0         0            0   
8834                0                              0         0            0   

      yellowish coloration skin white eye  yellowish skin  \
0                                       0               0   
1                                       0               0   
2                                       0               0   
3                                       0               0   
4                        

In [12]:
X = df.iloc[:,1:]
y = df_mod.iloc[:,0]

In [13]:
y

0         0
1         0
2         0
3         0
4         0
       ... 
8830    260
8831    260
8832    260
8833    260
8834    260
Name: label_dis, Length: 8835, dtype: int64

In [14]:
X.iloc[1,:].shape

(489,)

In [100]:
X_train1 = X_train.values

In [82]:
X_train1[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [108]:
len(list(X_train.iloc[1,:]))

489

In [144]:
from tensorflow.keras.utils import to_categorical

In [176]:
y_train = to_categorical(y_train)

In [177]:
y_test = to_categorical(y_test)

In [182]:
y1 = to_categorical(y)

In [128]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Flatten,Dropout


In [178]:
model = Sequential()

In [179]:
# model.add(Input(shape=(489,)))
model.add(Dense(489,activation = 'relu'))
model.add(Dense(350, activation = 'relu'))
# model1.add(Dropout(0.5))
model.add(Dense(300,activation = 'relu'))
# model1.add(Dropout(0.5))
# model.add(Dense(25,activation = 'relu'))
# model1.add(Dropout(0.5))
# model.add(Flatten())
model.add(Dense(261,activation='softmax'))

In [180]:
model.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' ,metrics = ['accuracy'])

In [ ]:
model.summary()

In [ ]:
model.fit(X,y1,batch_size =128 , epochs = 600)

In [163]:
y_pred = model.predict(X_test)

56/56 [==============================] - 0s 2ms/step


In [164]:
import numpy as np

In [169]:
y_pred

array([[0.0000000e+00, 0.0000000e+00, 1.6295913e-35, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [165]:
pred = [np.argmax(i) for i in y_pred]

In [170]:
len(pred)

1767

In [173]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [175]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       1.00      0.67      0.80         6
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         9
           7       1.00      0.83      0.91         6
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         4
          13       0.00      0.00      0.00         1
          14       1.00      1.00      1.00         2
          15       0.95      0.92      0.94       104
          16       1.00      1.00      1.00         1
          17       0.00      0.00      0.00         1
          18       0.67      0.80      0.73         5
          19       0.50      0.67      0.57         3
          20       0.00      0.00      0.00         1
          21       0.83      1.00      0.91         5
          22       0.00    

/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/minicon

In [ ]:
print(classification_report(y_test,pred))

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model  = LogisticRegression()

In [19]:
model.fit(X,y)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import classification_report

In [23]:
prediction = model.predict_proba(X_test)

In [26]:
k = 5
diseases = list(set(df1['label_dis']))
diseases.sort()
topk = prediction[0].argsort()[-k:][::-1]

In [25]:
df1 = pd.read_csv('/Users/mrinmoymahato/hackathon_code/dis_sym_dataset_comb.csv')

In [29]:
topk

array([217, 186, 125, 200, 103])

In [47]:
top_diseases = []

In [48]:
for i in topk:

    print(diseases[i],prediction[0][i]*100)
    if(prediction[0][i]*100>3):
        top_diseases.append(diseases[i])


Scrapie 85.77822399552029
Porphyria 5.304149624023915
Japanese Encephalitis 4.543346796934373
Rabies 0.2837785787452653
Heat-Related Illnesses and Heat waves 0.25670700130773955


In [49]:
top_diseases

['Scrapie', 'Porphyria', 'Japanese Encephalitis']

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       1.00      0.67      0.80         6
           5       1.00      1.00      1.00         1
           7       1.00      0.67      0.80         3
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         4
          15       0.86      1.00      0.93        51
          17       1.00      1.00      1.00         1
          18       1.00      1.00      1.00         4
          20       0.00      0.00      0.00         1
          21       1.00      1.00      1.00         1
          24       1.00      1.00      1.00         3
          25       0.00      0.00      0.00         1
          26       1.00      1.00      1.00         1
          27       0.75      1.00      0.86         3
          28       0.00      0.00      0.00         1
          29       1.00      1.00      1.00         3
          31       1.00    

/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/minicon

In [21]:
from sklearn.svm import SVC

In [22]:
classifier = SVC()

In [23]:
classifier.fit(X,y)

SVC()

In [24]:
y_pred = classifier.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       1.00      0.67      0.80         6
           5       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         3
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         4
          15       0.67      0.98      0.79        51
          17       1.00      1.00      1.00         1
          18       1.00      1.00      1.00         4
          20       0.00      0.00      0.00         1
          21       1.00      1.00      1.00         1
          24       1.00      1.00      1.00         3
          25       0.00      0.00      0.00         1
          26       1.00      1.00      1.00         1
          27       0.75      1.00      0.86         3
          28       0.00      0.00      0.00         1
          29       1.00      1.00      1.00         3
          31       1.00    

/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/minicon

In [ ]:
classifier.predict(X_test.iloc[:,0])

In [26]:
X.iloc[:,0]

0       0
1       0
2       0
3       0
4       0
       ..
8830    0
8831    0
8832    0
8833    0
8834    0
Name: abdominal cramp, Length: 8835, dtype: int64

In [32]:
df.columns.values

array(['label_dis', 'abdominal cramp', 'abdominal distention',
       'abnormal behavior', 'abnormal bleeding', 'abnormal sensation',
       'abnormally frequent', 'abscess', 'aching', 'acne',
       'acquiring drinking alcohol taking lot time',
       'affected part turning white', 'anemia', 'anxiety', 'arm',
       'attack pain', 'back', 'bacterial infection', 'bad breath',
       'bad smelling thin vaginal discharge',
       'bad smelling vaginal discharge', 'barky cough', 'belching',
       'better sitting worse lying',
       'birth baby younger week gestational age', 'bleeding gum',
       'bleeding skin', 'blindness', 'blindness one eye',
       'blister sunlight', 'bloating', 'blood stool', 'blood urine',
       'bloody diarrhea', 'blue', 'bluish skin coloration',
       'blurred vision', 'blurry vision', 'body tremor', 'bone pain',
       'bowed leg', 'breakdown skeletal muscle', 'breathing problem',
       'bruising', 'burning', 'burning redness eye',
       'burning stabbing

In [37]:
print( i for i in enumerate(df.columns.values))

<generator object <genexpr> at 0x16dbf6f80>


In [33]:
symptoms_dict = {}

In [38]:
cnt = 0
for i in  df.columns.values:
    symptoms_dict[i] = cnt
    cnt = cnt + 1


In [39]:
symptoms_dict

{'label_dis': 0,
 'abdominal cramp': 1,
 'abdominal distention': 2,
 'abnormal behavior': 3,
 'abnormal bleeding': 4,
 'abnormal sensation': 5,
 'abnormally frequent': 6,
 'abscess': 7,
 'aching': 8,
 'acne': 9,
 'acquiring drinking alcohol taking lot time': 10,
 'affected part turning white': 11,
 'anemia': 12,
 'anxiety': 13,
 'arm': 14,
 'attack pain': 15,
 'back': 16,
 'bacterial infection': 17,
 'bad breath': 18,
 'bad smelling thin vaginal discharge': 19,
 'bad smelling vaginal discharge': 20,
 'barky cough': 21,
 'belching': 22,
 'better sitting worse lying': 23,
 'birth baby younger week gestational age': 24,
 'bleeding gum': 25,
 'bleeding skin': 26,
 'blindness': 27,
 'blindness one eye': 28,
 'blister sunlight': 29,
 'bloating': 30,
 'blood stool': 31,
 'blood urine': 32,
 'bloody diarrhea': 33,
 'blue': 34,
 'bluish skin coloration': 35,
 'blurred vision': 36,
 'blurry vision': 37,
 'body tremor': 38,
 'bone pain': 39,
 'bowed leg': 40,
 'breakdown skeletal muscle': 41,
 'b

In [28]:
df_norm = pd.read_csv('/Users/mrinmoymahato/hackathon_code/dis_sym_dataset_norm.csv')

In [26]:
import numpy as np

In [29]:
sys = np.array(df_norm.iloc[8,:])[1:]

In [31]:
sys

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [30]:
sys = sys.reshape(1,-1)

In [107]:
len(sys[0])

489

In [108]:
classifier.predict(sys)

/opt/miniconda3/envs/hackathon/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([260])

In [109]:
from sklearn.metrics import confusion_matrix

In [110]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 4, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 3, 0, 0],
       [0, 0, 0, ..., 0, 3, 0],
       [0, 0, 0, ..., 0, 0, 0]])